INSERT INTO news_articles (id, date, title, image, excerpt, category, read_time, author, content)
VALUES
(1, '19 August 2025', 'Engineering Excellence: A Smart Solution for Modern Projects', 'https://images.unsplash.com/photo-1485083269755-a7b559a4fe5e?w=900&auto=format&fit=crop&q=60', 'Discover how our innovative engineering approaches are transforming complex industrial challenges into streamlined, cost-effective solutions.', 'Engineering', '5 min read', 'GIC Engineering Team', '[{"type":"paragraph","text":"In today''s rapidly evolving industrial landscape, engineering excellence is no longer just about technical proficiency—it''s about delivering intelligent solutions that address complex challenges while optimizing cost, time, and resources."},{"type":"heading","text":"The Challenge of Modern Industrial Projects"},{"type":"paragraph","text":"Modern oil and gas projects face unprecedented challenges: stringent environmental regulations, volatile market conditions, aging infrastructure, and the need for rapid deployment."},{"type":"heading","text":"Our Smart Engineering Approach"},{"type":"paragraph","text":"Our smart engineering solutions integrate advanced modeling techniques, predictive analytics, and collaborative digital platforms."},{"type":"list","items":["Digital twin technology for real-time project visualization","AI-powered risk assessment and mitigation strategies","Integrated design and construction planning using BIM","Sustainable engineering practices","Modular design approaches that reduce construction time by up to 30%"]},{"type":"heading","text":"Real-World Impact"},{"type":"paragraph","text":"A recent offshore platform modernization project exemplifies our approach, saving our client over $2.3 million."}]'::jsonb),
(2, '19 August 2025', 'Affordable EPC Solutions Now Within Reach', 'https://plus.unsplash.com/premium_photo-1661963032306-91ef5261511d?w=900&auto=format&fit=crop&q=60', 'Learn about our comprehensive EPC services that deliver exceptional value without compromising on quality or safety standards.', 'EPC Solutions', '6 min read', 'GIC Project Management', '[{"type":"paragraph","text":"Engineering, Procurement, and Construction (EPC) projects have traditionally been associated with substantial capital investment and extended timelines."},{"type":"heading","text":"Our Integrated Approach"},{"type":"paragraph","text":"We have developed an integrated EPC methodology that breaks down traditional silos."},{"type":"list","items":["Concurrent engineering and procurement planning","Strategic supplier partnerships","Prefabrication and modular construction techniques","Risk-sharing commercial models","Value engineering workshops"]}]'::jsonb),
(3, '19 August 2025', 'How Engineering Innovation Shapes a Sustainable Future', 'https://images.unsplash.com/photo-1515344905723-babc01aac23d?w=900&auto=format&fit=crop&q=60', 'Explore our commitment to sustainable practices and how we integrate environmental responsibility into every project phase.', 'Sustainability', '7 min read', 'GIC Sustainability Team', '[{"type":"paragraph","text":"The oil and gas industry stands at a critical juncture as global pressure mounts to reduce carbon emissions."},{"type":"heading","text":"Sustainability as a Core Engineering Principle"},{"type":"paragraph","text":"We have integrated sustainability into every phase of our engineering process."},{"type":"heading","text":"Innovative Technologies Driving Change"},{"type":"list","items":["Advanced flare gas recovery systems","Solar-powered monitoring and control systems","Water recycling technologies","Biodegradable drilling fluids","Carbon capture and utilization systems"]}]'::jsonb),
(4, '19 August 2025', 'Projects that Define the Impact of Innovation', 'https://images.unsplash.com/photo-1474631245212-32dc3c8310c6?w=900&auto=format&fit=crop&q=60', 'A closer look at landmark projects showcasing cutting-edge technology and exceptional execution standards.', 'Projects', '8 min read', 'GIC Project Delivery', '[{"type":"paragraph","text":"Throughout our history, GIC Oil & Gas Services Limited has delivered landmark projects that have redefined industry standards."},{"type":"heading","text":"Offshore Platform Expansion: Pushing Boundaries"},{"type":"paragraph","text":"One of our most challenging projects involved expanding production capacity on an aging offshore platform."}]'::jsonb),
(5, '15 August 2025', 'Advancing Marine Operations with Next-Gen Equipment', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&q=80', 'Our latest marine and offshore equipment solutions are setting new benchmarks for safety and operational efficiency.', 'Marine', '5 min read', 'GIC Marine Division', '[{"type":"paragraph","text":"The marine and offshore sector demands equipment that can withstand harsh environmental conditions."},{"type":"heading","text":"Our Next-Generation Portfolio"},{"type":"list","items":["Smart winch systems with automated load monitoring","Advanced mooring systems","Subsea equipment with remote diagnostics","Deck machinery with IoT sensors"]}]'::jsonb),
(6, '12 August 2025', 'Strategic Procurement for Oil & Gas Excellence', 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1200&q=80', 'How strategic procurement planning reduces costs and ensures timely delivery of critical materials and equipment.', 'Procurement', '6 min read', 'GIC Procurement Team', '[{"type":"paragraph","text":"In the complex world of oil and gas projects, procurement is far more than purchasing equipment and materials."},{"type":"heading","text":"The Strategic Procurement Advantage"},{"type":"paragraph","text":"Our approach to procurement begins long before purchase orders are issued."}]'::jsonb),
(7, '10 August 2025', 'Construction Safety: Setting Industry Standards', 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=1200&q=80', 'Our rigorous safety protocols and training programs ensure zero-incident construction sites across all operations.', 'Safety', '7 min read', 'GIC Safety & Compliance', '[{"type":"paragraph","text":"In the oil and gas industry, there is no acceptable compromise on safety."},{"type":"heading","text":"Our Safety Philosophy"},{"type":"paragraph","text":"Our safety philosophy is simple yet comprehensive: all incidents are preventable."}]'::jsonb),
(8, '8 August 2025', 'Digital Transformation in Industrial Services', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=80', 'Leveraging digital tools and IoT solutions to enhance operational visibility and project management efficiency.', 'Technology', '6 min read', 'GIC Digital Innovation', '[{"type":"paragraph","text":"The oil and gas industry is undergoing a profound digital transformation."},{"type":"heading","text":"Our Digital Ecosystem"},{"type":"list","items":["Cloud-based project management platform","IoT sensors monitoring performance","AI-powered predictive analytics","Digital twin technology"]}]'::jsonb),
(9, '5 August 2025', 'Expanding Our Global Partner Network', 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&q=80', 'New strategic partnerships strengthen our capabilities and extend our reach across key international markets.', 'Partnerships', '5 min read', 'GIC Business Development', '[{"type":"paragraph","text":"In today''s interconnected global economy, strategic partnerships are essential."},{"type":"heading","text":"Strategic Partnership Philosophy"},{"type":"paragraph","text":"We approach partnerships strategically, seeking organizations that complement our capabilities."}]'::jsonb)
ON CONFLICT (id) DO NOTHING;

SELECT setval('news_articles_id_seq', (SELECT COALESCE(MAX(id), 0) FROM news_articles));

INSERT INTO projects (id, title, category, location, year, value, scope, image, status)
VALUES
(1, 'Oando - Road Rehabilitation', 'Onshore', 'Rivers State, Nigeria', '2024', '$1M', 'Major civil works and rehabilitation of Akiri main road to drilling facility.', 'https://plus.unsplash.com/premium_photo-1661943489715-ea5e9dac7852?q=80&w=2670&auto=format&fit=crop', 'Completed'),
(2, 'Aiteo - Pipe fabrication and Waste management', 'Pipeline', 'OML 27, Bayelsa State', '2023', '$3M', 'Pipe fabrication and Waste management', 'https://images.unsplash.com/photo-1689476814887-43b4a7dc34e8?q=80&w=2274&auto=format&fit=crop', 'Completed'),
(3, 'Shell - Waste Management', 'Processing', 'Bayelsa State, Nigeria', '2018', '$800k', 'Waste management and procurement of pipe flex', 'https://images.unsplash.com/photo-1718642482960-77cfc3a4e2e5?q=80&w=2274&auto=format&fit=crop', 'Completed'),
(4, 'Renaissance - Human Capital Development', 'Onshore', 'Onne, Rivers State', '2026', '$3M', 'Major civil works', 'https://images.unsplash.com/photo-1605475723788-08c82657b6af?q=80&w=2670&auto=format&fit=crop', 'Ongoing'),
(5, 'World bank - Erosion Control', 'QHSE', 'Owerri, Imo State, Nigeria.', '2014', '$250k', 'Procurement and Installation of equipment for erosion control.', 'https://images.unsplash.com/photo-1767690594466-eba6f79551b9?q=80&w=2670&auto=format&fit=crop', 'Completed'),
(6, 'Shell - Waste Management', 'Subsea', 'Kidney Island, Rivers State', '2009', '$1M', 'Waste Management', 'https://images.unsplash.com/photo-1584968329412-cf2026fc7c3d?q=80&w=2670&auto=format&fit=crop', 'Completed')
ON CONFLICT (id) DO NOTHING;

SELECT setval('projects_id_seq', (SELECT COALESCE(MAX(id), 0) FROM projects));
